controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    rmitbot_controller:
      type: mecanum_drive_controller/MecanumDriveController
      # reference_topic: /rmitbot_controller/cmd_vel
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


rmitbot_controller:
  ros__parameters:
      # swap the type here as well
    type: mecanum_drive_controller/MecanumDriveController
    log_level: DEBUG
    # reference:
    #   topic: /rmitbot_controller/cmd_vel
    # timeout for stale commands
    reference_timeout: 0.9

    # use_stamped_vel: true
    in_chained_mode: false
    # reference_topic: "/rmitbot_controller/cmd_vel"
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"


    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      # wheel_base: 0.3
      sum_of_robot_center_projection_on_X_Y_axis: 0.34645
      wheels_radius: 0.0485
      # wheel_separation_x: 0.316
      # wheel_separation_y: 0.332
      

         # Command handling
    # cmd_vel_timeout: 0.5
    # publish_limited_velocity: false
    # velocity_rolling_window_size: 10
    # publish_rate: 50.0
        # keep your TF settings
    tf_frame_prefix_enable: false
    tf_frame_prefix: ""
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_footprint

    # reuse your covariances
    pose_covariance_diagonal:   [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    twist_covariance_diagonal:  [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
    position_feedback: true
    open_loop: true


    #  # Velocity limits
    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: 25.
    # linear.x.min_velocity: -25.
    # linear.x.max_acceleration: 25.
    # linear.x.max_jerk: 5.
    # linear.x.min_jerk: -5.
    # linear.y.has_velocity_limits: false
    # linear.y.has_acceleration_limits: false
    # linear.y.has_jerk_limits: false
    # linear.y.max_velocity: 25.
    # linear.y.min_velocity: -25.
    # linear.y.max_acceleration: 25.
    # linear.y.max_jerk: 5.
    # linear.y.min_jerk: -5.
    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: 25.
    # angular.z.min_velocity: -25.
    # angular.z.max_acceleration: 25.
    # angular.z.min_acceleration: -25.
    # angular.z.max_jerk: 5.
    # angular.z.min_jerk: -5.
